# Generated by Django 5.2.1 on 2025-07-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
